---
title: "eHMIS EPI data quality report"
author: "GEEKS Group 3 fellows"
format: pdf
execute: 
  echo: false
  cache: true
  warning: false
---

# Monthly eHMIS EPI data quality report

```{r}
library(tidyverse)
library(reactable)
library(flextable)
library(scales)
library(sf)
library(geodata)
library(mapview)
library(ggspatial)
```

```{r}
data <- read.csv("./data/dhis2-data2.csv")

data_clean  <- data |> rowwise() |> 
  mutate(District = str_remove_all(District, " District"),
         missing_reports = Expected.reports - Actual.reports, 
         missing_reports = if_else(missing_reports == 0, FALSE, TRUE),
         neg_dropout_rate_dpt1_3 = if_else(dropout.rate >= 0, FALSE, TRUE),
         discrepancy_dpt3_pcv3 = DPT3 - PCV.3, 
         discrepancy_dpt3_pcv3 = if_else(discrepancy_dpt3_pcv3 == 0, FALSE, TRUE),
         neg_wastage_rates_dpt = if_else(wastage.rate >= 0, FALSE, TRUE),
         .keep = "unused") |> 
  filter( !(is.na(missing_reports)& is.na(neg_dropout_rate_dpt1_3)& is.na(discrepancy_dpt3_pcv3) & is.na(neg_wastage_rates_dpt)))

## 
final_df <- data_clean  |>  
  mutate(priorty_number = sum(missing_reports, neg_dropout_rate_dpt1_3, 
                            discrepancy_dpt3_pcv3, neg_wastage_rates_dpt, na.rm = T)) |> 
  arrange(desc(priorty_number))

```

```{r}
percentage <- function(indicator){
  round((sum(indicator, na.rm = T)/n())*100, digits= 1)
}


district_data <- final_df |> 
  group_by(District) |> 
  summarise(across(missing_reports:neg_wastage_rates_dpt, percentage)) |> 
  arrange(across(missing_reports:neg_wastage_rates_dpt, desc))

```

```{r}
national_summary <- district_data |> 
  mutate(missing_reports = if_else(missing_reports >= 50, TRUE, FALSE),
         neg_dropout_rate_dpt1_3 = if_else(neg_dropout_rate_dpt1_3 >= 50, TRUE, FALSE),
         discrepancy_dpt3_pcv3 = if_else(discrepancy_dpt3_pcv3 >= 50, TRUE, FALSE),
         neg_wastage_rates_dpt = if_else(neg_wastage_rates_dpt >= 50, TRUE, FALSE),
         .keep = "unused") |> 
  summarise(across(missing_reports:neg_wastage_rates_dpt, sum, na.rm = T))
  
```

```{r}
library(ggspatial)
library(sf)

threshold <- function(x){
  
  case_when(x <= 20 ~ "0 - 20", 
             x <= 40 ~ "20 - 40", 
             x <= 60 ~ "40 - 60", 
             x <= 80 ~ "60 - 80", 
             x <= 100 ~ "80 - 100"
             ) |> 
    factor(levels = c("0 - 20", "20 - 40", "40 - 60", "60 - 80","80 - 100"))
}

ug_geodata <- sf::read_sf("./shapefiles/local/") |> 
  st_as_sf()

plot_data <- ug_geodata |> 
  mutate(District = str_to_title(District), 
         District = str_replace(District, "Madi Okollo", "Madi-Okollo"), 
         District = str_replace(District, "Kassnda", "Kassanda"), 
         District = str_replace(District, "Ssembabule", "Sembabule"), 
         District = str_replace(District, "Namutunmba", "Namutumba")
      
         ) |>
  left_join(district_data, by = c("District" = "District")) |> 
  mutate(District = as.factor(District ), 
         across(missing_reports:neg_wastage_rates_dpt, threshold ))
```

```{r}
# Create custom labels - e.g. (0k-10k]
labs <- c(0, 20, 40, 60,80, 100)

cols <- c("0 - 20" =  "#1a9641", "20 - 40" = "#a6d96a", 
          "40 - 60" = "#ffffbf", "60 - 80" = "#fdae61",
          "80 - 100"= "#d7191c")

labs_plot <- paste0(labs[1:5],"-", labs[2:6])

plot_ug_map <- function(data, fill){
  
 ggplot(data) +
  geom_sf(data = data, aes(fill = {{fill}}, group = District),
          color = "white",
          linetype = 1) +
  geom_sf_text(data = data,aes(label = case_when({{fill}} == "80 - 100"~ District, NULL)),size = 2) +
    # Labs
    labs(title = NULL,
         fill = "%") +
    scale_fill_manual(values = cols
   #                    label = labs_plot,
  #                       guide = NULL
  #                       guide = guide_legend(direction = "horizontal",
  #                                         nrow = 1,
  #                                         label.position = "bottom")
  )+

  theme_void()+
    theme(legend.position = "none")
# theme(plot.caption = element_text(size = 7, face = "italic"),
#        legend.position = "bottom")
}
```

```{r}
bar_plot <- function(data, indicator){
  
  data |> 
  as_tibble() |>  
  count({{indicator}}, .drop = FALSE) |> 
  ggplot(aes(x = {{indicator}}, y = n, fill = {{indicator}}))+
  geom_col() +
 geom_label(aes(label = n),size = 2) +
  scale_fill_manual(values = cols, guide = NULL)+
    # Labs
    labs(title = NULL,
         y = "Number of districts",
         x = "Category",
         fill = "%") +
  theme_classic()
}
```

## Missing reports

```{r}
#| layout: [[55,-5, 40]]
#| fig-subcap: 
#|   - "Priortise districts in Red"
#|   - "Summary of the districts"
#|   
plot_ug_map(data = plot_data,fill = missing_reports)


bar_plot(data = plot_data, indicator = missing_reports)  
```

## Negative Dropout rate

```{r}
#| layout: [[55,-5, 40]]
#| fig-subcap: 
#|   - "Priortise districts in Red"
#|   - "Summary of the districts"
#|   
plot_ug_map(data = plot_data,fill = neg_dropout_rate_dpt1_3)

bar_plot(data = plot_data, indicator = neg_dropout_rate_dpt1_3)
```

## Discrepancy between DPT3 and PCV3

```{r}
#| layout: [[55,-5, 40]]
#| fig-subcap: 
#|   - "Priortise districts in Red"
#|   - "Summary of the districts"
#|   
plot_ug_map(data = plot_data,fill = discrepancy_dpt3_pcv3)

bar_plot(data = plot_data, indicator = discrepancy_dpt3_pcv3)
```

## Negative wastage rate for DPT

```{r}
#| layout: [[55,-5, 40]]
#| fig-subcap: 
#|   - "Priortise districts in Red"
#|   - "Summary of the districts"
#|   
plot_ug_map(data = plot_data,fill = neg_wastage_rates_dpt)
bar_plot(data = plot_data, indicator = neg_wastage_rates_dpt)
```
